export const FETCH_PRODUCTS_START="FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_STARTED="FETCH_PRODUCTS_STARTED";
export const FETCH_PRODUCTS_FAILED="FETCH_PRODUCTS_FAILED";
export const FETCH_USERS_START="FETCH_USERS_START";
export const FETCH_USERS_STARTED="FETCH_USERS_STARTED";
export const FETCH_USERS_FAILED="FETCH_USERS_FAILED";
